CREATE TABLE IF NOT EXISTS `categories` (
    `id` INTEGER PRIMARY KEY AUTOINCREMENT,
    `name` VARCHAR(255) NOT NULL,
    `created_at` INTEGER DEFAULT CURRENT_TIMESTAMP,
    `deleted_at` INTEGER DEFAULT NULL
)
