CREATE TABLE IF NOT EXISTS `companies` (
    `id` INTEGER PRIMARY KEY AUTOINCREMENT,
    `name` VARCHAR(255) NOT NULL,
    `email` VARCHAR(255) NOT NULL,
    `password` VARCHAR(255) NOT NULL,
    `available_terrains` TINYINT UNSIGNED DEFAULT 3,
    `is_admin` TINYINT DEFAULT 0,
    `last_login` TIMESTAMP DEFAULT NULL,
    `blocked_at` TIMESTAMP DEFAULT NULL,
    `deleted_at` TIMESTAMP DEFAULT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
